#!/usr/bin/env python3
"""
The syscall table in README.md, generated rather than maintained.

A hand-written list of 400-odd syscalls is a list that is wrong within a month,
and wrong in the direction that matters: it claims things are implemented that
are not. This reads the numbers and names from the kernel's own headers and the
status from NABI's tables, so it can only say what is true of the tree it was
run against.

Usage: util/gen_syscall_doc.py <asm-generic/unistd.h> <asm/unistd_64.h>
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kernel_headers


def kernel_names(path, generic=False):
    """{name: number} for the real syscalls in a header.

    Two of the __NR_ defines are not syscalls and have to be dropped, or the
    table invents rows for them and inflates the denominator: __NR_syscalls is
    the *count* of syscalls, and __NR_arch_specific_syscall is the base an
    architecture numbers its private ones from. The dispatch-table generator has
    always skipped them; this one did not, and listed 463 and 244 as calls NABI
    had failed to implement.

    Not every number is spelled as one. asm-generic reaches a third of its
    table through `#define __NR_<name> __NR3264_<name>`, and reading only the
    lines that end in digits silently drops every one of them - which is how
    `lseek`, `fcntl`, `mmap`, `fstat` and `sendfile` came to be listed as having
    no aarch64 number at all. The dispatch-table generator has always followed
    the indirection; this one now does too.
    """
    text = kernel_headers.resolve(path) if generic else open(path).read()
    nr3264 = {m.group(1): int(m.group(2))
              for m in re.finditer(r'#define\s+__NR3264_(\w+)\s+(\d+)', text)}
    out = {}
    for m in re.finditer(r'^#define\s+__NR_(\w+)\s+(\S+)\s*$', text, re.M):
        name, val = m.group(1), m.group(2)
        if name in ('syscalls', 'arch_specific_syscall'):
            continue
        if val.isdigit():
            out[name] = int(val)
        elif val.startswith('__NR3264_'):
            key = val[len('__NR3264_'):]
            if key in nr3264:
                out[name] = nr3264[key]
    return out


def dedupe(table, handlers):
    """Drop the spelling of a number that the dispatch table does not use.

    Following the __NR3264_ indirection picks up both sides of the header's
    32-bit split, so one number arrives under two names - `lseek` and `llseek`,
    `fcntl` and `fcntl64`, `sendfile` and `sendfile64`. They are one call, and
    listing both would count it twice and claim an alias this architecture does
    not expose. Whichever name the dispatch table dispatches is the one kept, so
    the doc and the table cannot disagree about what exists.
    """
    by_nr = {}
    for name, nr in table.items():
        by_nr.setdefault(nr, []).append(name)
    out = dict(table)
    for names in by_nr.values():
        if len(names) < 2:
            continue
        wins = [n for n in names if n in handlers]
        # Whichever the dispatch table uses; failing that the plain spelling,
        # since the alias is always the longer one - truncate64 for truncate,
        # llseek for lseek - and neither having a handler is no reason to list
        # the same call twice.
        keep = wins[0] if len(wins) == 1 else min(names, key=lambda n: (len(n), n))
        for n in names:
            if n != keep:
                del out[n]
    return out


def refuses():
    """Syscalls with a handler whose whole answer is "this does not exist".

    They are not gaps and should not be counted as coverage. Most are calls
    Linux itself does not implement (uselib, tuxcall, the *_old epoll pair) or
    that belong to another architecture; rseq is the one that could have been
    implemented and deliberately is not - see src/proc/rseq.c.
    """
    import glob
    out = {'rseq'}
    for path in glob.glob('src/**/*.c', recursive=True):
        for m in re.finditer(r'DEFINE_NOT_IMPLEMENTED_SYSCALL\(\s*(\w+)',
                             open(path).read()):
            out.add(m.group(1))
    return out


def implemented(path):
    got = set()
    for line in open(path):
        m = re.match(r'\s*SYSCALL\((\d+),\s*(\w+)\)', line)
        if m and m.group(2) != 'unimplemented':
            got.add(m.group(2))
    return got


def main():
    ia = implemented('include/syscall_arm64.h')
    ix = implemented('include/syscall_x86.h')
    a64 = dedupe(kernel_names(sys.argv[1], generic=True), ia)
    x64 = kernel_names(sys.argv[2])
    no = refuses()

    names = sorted(set(a64) | set(x64))
    have = {n for n in names if (n in ia or n in ix) and n not in no}
    deliberate = {n for n in names if n in no}
    done = len(have)

    o = sys.stdout
    print("<!-- GENERATED by util/gen_syscall_doc.py - do not edit by hand. -->")
    print()
    print(f"**{done} of {len(names)} implemented.**")
    print()
    print("| | |")
    print("|---|---|")
    print("| ✅ | implemented |")
    print(f"| ⊘ | answered deliberately, and the answer is `ENOSYS` "
          f"({len(deliberate)} calls) — most are ones Linux does not implement "
          f"either; `rseq` is the one that could have been and is not, for the "
          f"reason in `src/proc/rseq.c` |")
    print("| · | no handler; the unknown-syscall path, which is also `ENOSYS` |")
    print()
    print("A dash in a number column means that architecture has no such call.")
    print()
    print("<details>")
    print(f"<summary>The full table ({len(names)} calls)</summary>")
    print()
    print("| Syscall | aarch64 | x86-64 | NABI |")
    print("|---|---:|---:|:---:|")
    for n in names:
        na = a64.get(n)
        nx = x64.get(n)
        # Implemented is per-handler, not per-arch: the same C function serves
        # both tables, so a name is done or it is not.
        mark = "⊘" if n in deliberate else ("✅" if n in have else "·")
        print(f"| `{n}` | {na if na is not None else '—'} "
              f"| {nx if nx is not None else '—'} | {mark} |")
    print()
    print("</details>")


main()
