#!/usr/bin/env python3
"""
The syscall table in README.md, generated rather than maintained.

A hand-written list of 400-odd syscalls is a list that is wrong within a month,
and wrong in the direction that matters: it claims things are implemented that
are not. This reads the numbers and names from the kernel's own headers and the
status from NABI's tables, so it can only say what is true of the tree it was
run against.

Usage: util/gen_syscall_doc.py <asm-generic/unistd.h> <asm/unistd_64.h>
"""
import re
import sys


def kernel_names(path):
    out = {}
    for line in open(path):
        m = re.match(r'#define\s+__NR_(\w+)\s+(\d+)\s*$', line)
        if m:
            out[m.group(1)] = int(m.group(2))
    return out


def refuses():
    """Syscalls with a handler whose whole answer is "this does not exist".

    They are not gaps and should not be counted as coverage. Most are calls
    Linux itself does not implement (uselib, tuxcall, the *_old epoll pair) or
    that belong to another architecture; rseq is the one that could have been
    implemented and deliberately is not - see src/proc/rseq.c.
    """
    import glob
    out = {'rseq'}
    for path in glob.glob('src/**/*.c', recursive=True):
        for m in re.finditer(r'DEFINE_NOT_IMPLEMENTED_SYSCALL\(\s*(\w+)',
                             open(path).read()):
            out.add(m.group(1))
    return out


def implemented(path):
    got = set()
    for line in open(path):
        m = re.match(r'\s*SYSCALL\((\d+),\s*(\w+)\)', line)
        if m and m.group(2) != 'unimplemented':
            got.add(m.group(2))
    return got


def main():
    a64 = kernel_names(sys.argv[1])
    x64 = kernel_names(sys.argv[2])
    ia = implemented('include/syscall_arm64.h')
    ix = implemented('include/syscall_x86.h')
    no = refuses()

    names = sorted(set(a64) | set(x64))
    have = {n for n in names if (n in ia or n in ix) and n not in no}
    deliberate = {n for n in names if n in no}
    done = len(have)

    o = sys.stdout
    print("<!-- GENERATED by util/gen_syscall_doc.py - do not edit by hand. -->")
    print()
    print(f"**{done} of {len(names)} implemented.**")
    print()
    print("| | |")
    print("|---|---|")
    print("| ✅ | implemented |")
    print(f"| ⊘ | answered deliberately, and the answer is `ENOSYS` "
          f"({len(deliberate)} calls) — most are ones Linux does not implement "
          f"either; `rseq` is the one that could have been and is not, for the "
          f"reason in `src/proc/rseq.c` |")
    print("| · | no handler; the unknown-syscall path, which is also `ENOSYS` |")
    print()
    print("A dash in a number column means that architecture has no such call.")
    print()
    print("<details>")
    print(f"<summary>The full table ({len(names)} calls)</summary>")
    print()
    print("| Syscall | aarch64 | x86-64 | NABI |")
    print("|---|---:|---:|:---:|")
    for n in names:
        na = a64.get(n)
        nx = x64.get(n)
        # Implemented is per-handler, not per-arch: the same C function serves
        # both tables, so a name is done or it is not.
        mark = "⊘" if n in deliberate else ("✅" if n in have else "·")
        print(f"| `{n}` | {na if na is not None else '—'} "
              f"| {nx if nx is not None else '—'} | {mark} |")
    print()
    print("</details>")


main()
