/*
 * x86-64 syscall table - GENERATED, do not edit by hand.
 * Regenerate: util/gen_syscall_table_x86.py <asm/unistd_64.h>
 */
#include <stdint.h>

#define SYSCALLS \
  SYSCALL(0, read) \
  SYSCALL(1, write) \
  SYSCALL(2, open) \
  SYSCALL(3, close) \
  SYSCALL(4, stat) \
  SYSCALL(5, fstat) \
  SYSCALL(6, lstat) \
  SYSCALL(7, poll) \
  SYSCALL(8, lseek) \
  SYSCALL(9, mmap) \
  SYSCALL(10, mprotect) \
  SYSCALL(11, munmap) \
  SYSCALL(12, brk) \
  SYSCALL(13, rt_sigaction) \
  SYSCALL(14, rt_sigprocmask) \
  SYSCALL(15, rt_sigreturn) \
  SYSCALL(16, ioctl) \
  SYSCALL(17, pread64) \
  SYSCALL(18, pwrite64) \
  SYSCALL(19, readv) \
  SYSCALL(20, writev) \
  SYSCALL(21, access) \
  SYSCALL(22, pipe) \
  SYSCALL(23, select) \
  SYSCALL(24, sched_yield) \
  SYSCALL(25, mremap) \
  SYSCALL(26, msync) \
  SYSCALL(27, unimplemented) \
  SYSCALL(28, madvise) \
  SYSCALL(29, shmget) \
  SYSCALL(30, shmat) \
  SYSCALL(31, shmctl) \
  SYSCALL(32, dup) \
  SYSCALL(33, dup2) \
  SYSCALL(34, unimplemented) \
  SYSCALL(35, nanosleep) \
  SYSCALL(36, getitimer) \
  SYSCALL(37, alarm) \
  SYSCALL(38, setitimer) \
  SYSCALL(39, getpid) \
  SYSCALL(40, sendfile) \
  SYSCALL(41, socket) \
  SYSCALL(42, connect) \
  SYSCALL(43, accept) \
  SYSCALL(44, sendto) \
  SYSCALL(45, recvfrom) \
  SYSCALL(46, sendmsg) \
  SYSCALL(47, recvmsg) \
  SYSCALL(48, shutdown) \
  SYSCALL(49, bind) \
  SYSCALL(50, listen) \
  SYSCALL(51, getsockname) \
  SYSCALL(52, getpeername) \
  SYSCALL(53, socketpair) \
  SYSCALL(54, setsockopt) \
  SYSCALL(55, getsockopt) \
  SYSCALL(56, clone) \
  SYSCALL(57, fork) \
  SYSCALL(58, vfork) \
  SYSCALL(59, execve) \
  SYSCALL(60, exit) \
  SYSCALL(61, wait4) \
  SYSCALL(62, kill) \
  SYSCALL(63, uname) \
  SYSCALL(64, semget) \
  SYSCALL(65, semop) \
  SYSCALL(66, semctl) \
  SYSCALL(67, shmdt) \
  SYSCALL(68, msgget) \
  SYSCALL(69, msgsnd) \
  SYSCALL(70, msgrcv) \
  SYSCALL(71, msgctl) \
  SYSCALL(72, fcntl) \
  SYSCALL(73, flock) \
  SYSCALL(74, fsync) \
  SYSCALL(75, fdatasync) \
  SYSCALL(76, unimplemented) \
  SYSCALL(77, ftruncate) \
  SYSCALL(78, getdents) \
  SYSCALL(79, getcwd) \
  SYSCALL(80, chdir) \
  SYSCALL(81, fchdir) \
  SYSCALL(82, rename) \
  SYSCALL(83, mkdir) \
  SYSCALL(84, rmdir) \
  SYSCALL(85, creat) \
  SYSCALL(86, link) \
  SYSCALL(87, unlink) \
  SYSCALL(88, symlink) \
  SYSCALL(89, readlink) \
  SYSCALL(90, chmod) \
  SYSCALL(91, fchmod) \
  SYSCALL(92, chown) \
  SYSCALL(93, fchown) \
  SYSCALL(94, lchown) \
  SYSCALL(95, umask) \
  SYSCALL(96, gettimeofday) \
  SYSCALL(97, getrlimit) \
  SYSCALL(98, getrusage) \
  SYSCALL(99, sysinfo) \
  SYSCALL(100, unimplemented) \
  SYSCALL(101, ptrace) \
  SYSCALL(102, getuid) \
  SYSCALL(103, syslog) \
  SYSCALL(104, getgid) \
  SYSCALL(105, setuid) \
  SYSCALL(106, setgid) \
  SYSCALL(107, geteuid) \
  SYSCALL(108, getegid) \
  SYSCALL(109, setpgid) \
  SYSCALL(110, getppid) \
  SYSCALL(111, getpgrp) \
  SYSCALL(112, setsid) \
  SYSCALL(113, unimplemented) \
  SYSCALL(114, unimplemented) \
  SYSCALL(115, getgroups) \
  SYSCALL(116, setgroups) \
  SYSCALL(117, setresuid) \
  SYSCALL(118, getresuid) \
  SYSCALL(119, setresgid) \
  SYSCALL(120, getresgid) \
  SYSCALL(121, getpgid) \
  SYSCALL(122, unimplemented) \
  SYSCALL(123, unimplemented) \
  SYSCALL(124, getsid) \
  SYSCALL(125, capget) \
  SYSCALL(126, unimplemented) \
  SYSCALL(127, rt_sigpending) \
  SYSCALL(128, unimplemented) \
  SYSCALL(129, unimplemented) \
  SYSCALL(130, rt_sigsuspend) \
  SYSCALL(131, sigaltstack) \
  SYSCALL(132, utime) \
  SYSCALL(133, mknod) \
  SYSCALL(134, uselib) \
  SYSCALL(135, unimplemented) \
  SYSCALL(136, unimplemented) \
  SYSCALL(137, statfs) \
  SYSCALL(138, fstatfs) \
  SYSCALL(139, sysfs) \
  SYSCALL(140, getpriority) \
  SYSCALL(141, setpriority) \
  SYSCALL(142, sched_setparam) \
  SYSCALL(143, sched_getparam) \
  SYSCALL(144, sched_setscheduler) \
  SYSCALL(145, sched_getscheduler) \
  SYSCALL(146, sched_get_priority_max) \
  SYSCALL(147, sched_get_priority_min) \
  SYSCALL(148, sched_rr_get_interval) \
  SYSCALL(149, mlock) \
  SYSCALL(150, munlock) \
  SYSCALL(151, unimplemented) \
  SYSCALL(152, unimplemented) \
  SYSCALL(153, unimplemented) \
  SYSCALL(154, unimplemented) \
  SYSCALL(155, unimplemented) \
  SYSCALL(156, unimplemented) \
  SYSCALL(157, prctl) \
  SYSCALL(158, arch_prctl) \
  SYSCALL(159, unimplemented) \
  SYSCALL(160, setrlimit) \
  SYSCALL(161, chroot) \
  SYSCALL(162, sync) \
  SYSCALL(163, unimplemented) \
  SYSCALL(164, unimplemented) \
  SYSCALL(165, mount) \
  SYSCALL(166, umount2) \
  SYSCALL(167, unimplemented) \
  SYSCALL(168, unimplemented) \
  SYSCALL(169, unimplemented) \
  SYSCALL(170, sethostname) \
  SYSCALL(171, setdomainname) \
  SYSCALL(172, unimplemented) \
  SYSCALL(173, unimplemented) \
  SYSCALL(174, unimplemented) \
  SYSCALL(175, unimplemented) \
  SYSCALL(176, unimplemented) \
  SYSCALL(177, unimplemented) \
  SYSCALL(178, unimplemented) \
  SYSCALL(179, unimplemented) \
  SYSCALL(180, nfsservctl) \
  SYSCALL(181, getpmsg) \
  SYSCALL(182, putpmsg) \
  SYSCALL(183, afs_syscall) \
  SYSCALL(184, tuxcall) \
  SYSCALL(185, security) \
  SYSCALL(186, gettid) \
  SYSCALL(187, unimplemented) \
  SYSCALL(188, setxattr) \
  SYSCALL(189, lsetxattr) \
  SYSCALL(190, fsetxattr) \
  SYSCALL(191, getxattr) \
  SYSCALL(192, lgetxattr) \
  SYSCALL(193, fgetxattr) \
  SYSCALL(194, listxattr) \
  SYSCALL(195, llistxattr) \
  SYSCALL(196, flistxattr) \
  SYSCALL(197, removexattr) \
  SYSCALL(198, lremovexattr) \
  SYSCALL(199, fremovexattr) \
  SYSCALL(200, tkill) \
  SYSCALL(201, time) \
  SYSCALL(202, futex) \
  SYSCALL(203, sched_setaffinity) \
  SYSCALL(204, sched_getaffinity) \
  SYSCALL(205, set_thread_area) \
  SYSCALL(206, io_setup) \
  SYSCALL(207, io_destroy) \
  SYSCALL(208, io_getevents) \
  SYSCALL(209, io_submit) \
  SYSCALL(210, io_cancel) \
  SYSCALL(211, get_thread_area) \
  SYSCALL(212, unimplemented) \
  SYSCALL(213, unimplemented) \
  SYSCALL(214, epoll_ctl_old) \
  SYSCALL(215, epoll_wait_old) \
  SYSCALL(216, unimplemented) \
  SYSCALL(217, getdents64) \
  SYSCALL(218, set_tid_address) \
  SYSCALL(219, unimplemented) \
  SYSCALL(220, semtimedop) \
  SYSCALL(221, fadvise64) \
  SYSCALL(222, timer_create) \
  SYSCALL(223, timer_settime) \
  SYSCALL(224, timer_gettime) \
  SYSCALL(225, timer_getoverrun) \
  SYSCALL(226, timer_delete) \
  SYSCALL(227, unimplemented) \
  SYSCALL(228, clock_gettime) \
  SYSCALL(229, clock_getres) \
  SYSCALL(230, clock_nanosleep) \
  SYSCALL(231, exit_group) \
  SYSCALL(232, unimplemented) \
  SYSCALL(233, epoll_ctl) \
  SYSCALL(234, tgkill) \
  SYSCALL(235, utimes) \
  SYSCALL(236, vserver) \
  SYSCALL(237, unimplemented) \
  SYSCALL(238, unimplemented) \
  SYSCALL(239, get_mempolicy) \
  SYSCALL(240, mq_open) \
  SYSCALL(241, mq_unlink) \
  SYSCALL(242, mq_timedsend) \
  SYSCALL(243, mq_timedreceive) \
  SYSCALL(244, mq_notify) \
  SYSCALL(245, mq_getsetattr) \
  SYSCALL(246, unimplemented) \
  SYSCALL(247, unimplemented) \
  SYSCALL(248, unimplemented) \
  SYSCALL(249, unimplemented) \
  SYSCALL(250, unimplemented) \
  SYSCALL(251, ioprio_set) \
  SYSCALL(252, ioprio_get) \
  SYSCALL(253, inotify_init) \
  SYSCALL(254, inotify_add_watch) \
  SYSCALL(255, inotify_rm_watch) \
  SYSCALL(256, unimplemented) \
  SYSCALL(257, openat) \
  SYSCALL(258, mkdirat) \
  SYSCALL(259, mknodat) \
  SYSCALL(260, fchownat) \
  SYSCALL(261, unimplemented) \
  SYSCALL(262, newfstatat) \
  SYSCALL(263, unlinkat) \
  SYSCALL(264, renameat) \
  SYSCALL(265, linkat) \
  SYSCALL(266, symlinkat) \
  SYSCALL(267, readlinkat) \
  SYSCALL(268, fchmodat) \
  SYSCALL(269, faccessat) \
  SYSCALL(270, pselect6) \
  SYSCALL(271, ppoll) \
  SYSCALL(272, unshare) \
  SYSCALL(273, set_robust_list) \
  SYSCALL(274, get_robust_list) \
  SYSCALL(275, splice) \
  SYSCALL(276, tee) \
  SYSCALL(277, sync_file_range) \
  SYSCALL(278, vmsplice) \
  SYSCALL(279, unimplemented) \
  SYSCALL(280, utimensat) \
  SYSCALL(281, epoll_pwait) \
  SYSCALL(282, unimplemented) \
  SYSCALL(283, timerfd_create) \
  SYSCALL(284, unimplemented) \
  SYSCALL(285, fallocate) \
  SYSCALL(286, timerfd_settime) \
  SYSCALL(287, timerfd_gettime) \
  SYSCALL(288, unimplemented) \
  SYSCALL(289, unimplemented) \
  SYSCALL(290, eventfd2) \
  SYSCALL(291, epoll_create1) \
  SYSCALL(292, dup3) \
  SYSCALL(293, pipe2) \
  SYSCALL(294, inotify_init1) \
  SYSCALL(295, unimplemented) \
  SYSCALL(296, unimplemented) \
  SYSCALL(297, unimplemented) \
  SYSCALL(298, unimplemented) \
  SYSCALL(299, unimplemented) \
  SYSCALL(300, fanotify_init) \
  SYSCALL(301, fanotify_mark) \
  SYSCALL(302, prlimit64) \
  SYSCALL(303, name_to_handle_at) \
  SYSCALL(304, open_by_handle_at) \
  SYSCALL(305, unimplemented) \
  SYSCALL(306, syncfs) \
  SYSCALL(307, sendmmsg) \
  SYSCALL(308, setns) \
  SYSCALL(309, unimplemented) \
  SYSCALL(310, unimplemented) \
  SYSCALL(311, unimplemented) \
  SYSCALL(312, unimplemented) \
  SYSCALL(313, unimplemented) \
  SYSCALL(314, unimplemented) \
  SYSCALL(315, unimplemented) \
  SYSCALL(316, unimplemented) \
  SYSCALL(317, unimplemented) \
  SYSCALL(318, getrandom) \
  SYSCALL(319, unimplemented) \
  SYSCALL(320, unimplemented) \
  SYSCALL(321, unimplemented) \
  SYSCALL(322, unimplemented) \
  SYSCALL(323, unimplemented) \
  SYSCALL(324, unimplemented) \
  SYSCALL(325, unimplemented) \
  SYSCALL(326, copy_file_range) \
  SYSCALL(327, unimplemented) \
  SYSCALL(328, unimplemented) \
  SYSCALL(329, unimplemented) \
  SYSCALL(330, unimplemented) \
  SYSCALL(331, unimplemented) \
  SYSCALL(332, statx) \
  SYSCALL(333, io_pgetevents) \
  SYSCALL(334, rseq) \
  SYSCALL(335, unimplemented) \
  SYSCALL(336, unimplemented) \
  SYSCALL(337, unimplemented) \
  SYSCALL(338, unimplemented) \
  SYSCALL(339, unimplemented) \
  SYSCALL(340, unimplemented) \
  SYSCALL(341, unimplemented) \
  SYSCALL(342, unimplemented) \
  SYSCALL(343, unimplemented) \
  SYSCALL(344, unimplemented) \
  SYSCALL(345, unimplemented) \
  SYSCALL(346, unimplemented) \
  SYSCALL(347, unimplemented) \
  SYSCALL(348, unimplemented) \
  SYSCALL(349, unimplemented) \
  SYSCALL(350, unimplemented) \
  SYSCALL(351, unimplemented) \
  SYSCALL(352, unimplemented) \
  SYSCALL(353, unimplemented) \
  SYSCALL(354, unimplemented) \
  SYSCALL(355, unimplemented) \
  SYSCALL(356, unimplemented) \
  SYSCALL(357, unimplemented) \
  SYSCALL(358, unimplemented) \
  SYSCALL(359, unimplemented) \
  SYSCALL(360, unimplemented) \
  SYSCALL(361, unimplemented) \
  SYSCALL(362, unimplemented) \
  SYSCALL(363, unimplemented) \
  SYSCALL(364, unimplemented) \
  SYSCALL(365, unimplemented) \
  SYSCALL(366, unimplemented) \
  SYSCALL(367, unimplemented) \
  SYSCALL(368, unimplemented) \
  SYSCALL(369, unimplemented) \
  SYSCALL(370, unimplemented) \
  SYSCALL(371, unimplemented) \
  SYSCALL(372, unimplemented) \
  SYSCALL(373, unimplemented) \
  SYSCALL(374, unimplemented) \
  SYSCALL(375, unimplemented) \
  SYSCALL(376, unimplemented) \
  SYSCALL(377, unimplemented) \
  SYSCALL(378, unimplemented) \
  SYSCALL(379, unimplemented) \
  SYSCALL(380, unimplemented) \
  SYSCALL(381, unimplemented) \
  SYSCALL(382, unimplemented) \
  SYSCALL(383, unimplemented) \
  SYSCALL(384, unimplemented) \
  SYSCALL(385, unimplemented) \
  SYSCALL(386, unimplemented) \
  SYSCALL(387, unimplemented) \
  SYSCALL(388, unimplemented) \
  SYSCALL(389, unimplemented) \
  SYSCALL(390, unimplemented) \
  SYSCALL(391, unimplemented) \
  SYSCALL(392, unimplemented) \
  SYSCALL(393, unimplemented) \
  SYSCALL(394, unimplemented) \
  SYSCALL(395, unimplemented) \
  SYSCALL(396, unimplemented) \
  SYSCALL(397, unimplemented) \
  SYSCALL(398, unimplemented) \
  SYSCALL(399, unimplemented) \
  SYSCALL(400, unimplemented) \
  SYSCALL(401, unimplemented) \
  SYSCALL(402, unimplemented) \
  SYSCALL(403, unimplemented) \
  SYSCALL(404, unimplemented) \
  SYSCALL(405, unimplemented) \
  SYSCALL(406, unimplemented) \
  SYSCALL(407, unimplemented) \
  SYSCALL(408, unimplemented) \
  SYSCALL(409, unimplemented) \
  SYSCALL(410, unimplemented) \
  SYSCALL(411, unimplemented) \
  SYSCALL(412, unimplemented) \
  SYSCALL(413, unimplemented) \
  SYSCALL(414, unimplemented) \
  SYSCALL(415, unimplemented) \
  SYSCALL(416, unimplemented) \
  SYSCALL(417, unimplemented) \
  SYSCALL(418, unimplemented) \
  SYSCALL(419, unimplemented) \
  SYSCALL(420, unimplemented) \
  SYSCALL(421, unimplemented) \
  SYSCALL(422, unimplemented) \
  SYSCALL(423, unimplemented) \
  SYSCALL(424, unimplemented) \
  SYSCALL(425, io_uring_setup) \
  SYSCALL(426, io_uring_enter) \
  SYSCALL(427, io_uring_register) \
  SYSCALL(428, unimplemented) \
  SYSCALL(429, unimplemented) \
  SYSCALL(430, unimplemented) \
  SYSCALL(431, unimplemented) \
  SYSCALL(432, unimplemented) \
  SYSCALL(433, unimplemented) \
  SYSCALL(434, unimplemented) \
  SYSCALL(435, clone3) \
  SYSCALL(436, unimplemented) \
  SYSCALL(437, openat2) \
  SYSCALL(438, unimplemented) \
  SYSCALL(439, faccessat2) \
  SYSCALL(440, unimplemented) \
  SYSCALL(441, unimplemented) \
  SYSCALL(442, unimplemented) \
  SYSCALL(443, unimplemented) \
  SYSCALL(444, unimplemented) \
  SYSCALL(445, unimplemented) \
  SYSCALL(446, unimplemented) \
  SYSCALL(447, unimplemented) \
  SYSCALL(448, unimplemented) \
  SYSCALL(449, futex_waitv) \
  SYSCALL(450, unimplemented) \
  SYSCALL(451, unimplemented) \
  SYSCALL(452, unimplemented) \
  SYSCALL(453, unimplemented) \
  SYSCALL(454, futex_wake) \
  SYSCALL(455, futex_wait) \
  SYSCALL(456, futex_requeue) \
  SYSCALL(457, unimplemented) \
  SYSCALL(458, unimplemented) \
  SYSCALL(459, unimplemented) \
  SYSCALL(460, unimplemented) \
  SYSCALL(461, unimplemented) \
  SYSCALL(462, unimplemented) \

#define NR_SYSCALLS 463
