/*
 * aarch64 syscall table - GENERATED, do not edit by hand.
 * Regenerate: util/gen_syscall_table.py <unistd_generic.h>
 * See PORTING-arm64.md section 3.2.
 */
#include <stdint.h>

#define SYSCALLS \
  SYSCALL(0, io_setup) \
  SYSCALL(1, io_destroy) \
  SYSCALL(2, io_submit) \
  SYSCALL(3, io_cancel) \
  SYSCALL(4, io_getevents) \
  SYSCALL(5, setxattr) \
  SYSCALL(6, lsetxattr) \
  SYSCALL(7, fsetxattr) \
  SYSCALL(8, getxattr) \
  SYSCALL(9, lgetxattr) \
  SYSCALL(10, fgetxattr) \
  SYSCALL(11, listxattr) \
  SYSCALL(12, llistxattr) \
  SYSCALL(13, flistxattr) \
  SYSCALL(14, removexattr) \
  SYSCALL(15, lremovexattr) \
  SYSCALL(16, fremovexattr) \
  SYSCALL(17, getcwd) \
  SYSCALL(18, unimplemented) \
  SYSCALL(19, eventfd2) \
  SYSCALL(20, epoll_create1) \
  SYSCALL(21, epoll_ctl) \
  SYSCALL(22, epoll_pwait) \
  SYSCALL(23, dup) \
  SYSCALL(24, dup3) \
  SYSCALL(25, fcntl) \
  SYSCALL(26, inotify_init1) \
  SYSCALL(27, inotify_add_watch) \
  SYSCALL(28, inotify_rm_watch) \
  SYSCALL(29, ioctl) \
  SYSCALL(30, unimplemented) \
  SYSCALL(31, unimplemented) \
  SYSCALL(32, flock) \
  SYSCALL(33, mknodat) \
  SYSCALL(34, mkdirat) \
  SYSCALL(35, unlinkat) \
  SYSCALL(36, symlinkat) \
  SYSCALL(37, linkat) \
  SYSCALL(38, renameat) \
  SYSCALL(39, umount2) \
  SYSCALL(40, mount) \
  SYSCALL(41, unimplemented) \
  SYSCALL(42, nfsservctl) \
  SYSCALL(43, statfs) \
  SYSCALL(44, fstatfs) \
  SYSCALL(45, unimplemented) \
  SYSCALL(46, ftruncate) \
  SYSCALL(47, fallocate) \
  SYSCALL(48, faccessat) \
  SYSCALL(49, chdir) \
  SYSCALL(50, fchdir) \
  SYSCALL(51, chroot) \
  SYSCALL(52, fchmod) \
  SYSCALL(53, fchmodat) \
  SYSCALL(54, fchownat) \
  SYSCALL(55, fchown) \
  SYSCALL(56, openat) \
  SYSCALL(57, close) \
  SYSCALL(58, unimplemented) \
  SYSCALL(59, pipe2) \
  SYSCALL(60, unimplemented) \
  SYSCALL(61, getdents64) \
  SYSCALL(62, lseek) \
  SYSCALL(63, read) \
  SYSCALL(64, write) \
  SYSCALL(65, readv) \
  SYSCALL(66, writev) \
  SYSCALL(67, pread64) \
  SYSCALL(68, pwrite64) \
  SYSCALL(69, unimplemented) \
  SYSCALL(70, unimplemented) \
  SYSCALL(71, sendfile) \
  SYSCALL(72, pselect6) \
  SYSCALL(73, ppoll) \
  SYSCALL(74, unimplemented) \
  SYSCALL(75, vmsplice) \
  SYSCALL(76, splice) \
  SYSCALL(77, tee) \
  SYSCALL(78, readlinkat) \
  SYSCALL(79, newfstatat) \
  SYSCALL(80, fstat) \
  SYSCALL(81, sync) \
  SYSCALL(82, fsync) \
  SYSCALL(83, fdatasync) \
  SYSCALL(84, sync_file_range) \
  SYSCALL(85, timerfd_create) \
  SYSCALL(86, timerfd_settime) \
  SYSCALL(87, timerfd_gettime) \
  SYSCALL(88, utimensat) \
  SYSCALL(89, unimplemented) \
  SYSCALL(90, capget) \
  SYSCALL(91, unimplemented) \
  SYSCALL(92, unimplemented) \
  SYSCALL(93, exit) \
  SYSCALL(94, exit_group) \
  SYSCALL(95, unimplemented) \
  SYSCALL(96, set_tid_address) \
  SYSCALL(97, unshare) \
  SYSCALL(98, futex) \
  SYSCALL(99, set_robust_list) \
  SYSCALL(100, get_robust_list) \
  SYSCALL(101, nanosleep) \
  SYSCALL(102, getitimer) \
  SYSCALL(103, setitimer) \
  SYSCALL(104, unimplemented) \
  SYSCALL(105, unimplemented) \
  SYSCALL(106, unimplemented) \
  SYSCALL(107, timer_create) \
  SYSCALL(108, timer_gettime) \
  SYSCALL(109, timer_getoverrun) \
  SYSCALL(110, timer_settime) \
  SYSCALL(111, timer_delete) \
  SYSCALL(112, unimplemented) \
  SYSCALL(113, clock_gettime) \
  SYSCALL(114, clock_getres) \
  SYSCALL(115, clock_nanosleep) \
  SYSCALL(116, syslog) \
  SYSCALL(117, ptrace) \
  SYSCALL(118, sched_setparam) \
  SYSCALL(119, sched_setscheduler) \
  SYSCALL(120, sched_getscheduler) \
  SYSCALL(121, sched_getparam) \
  SYSCALL(122, sched_setaffinity) \
  SYSCALL(123, sched_getaffinity) \
  SYSCALL(124, sched_yield) \
  SYSCALL(125, sched_get_priority_max) \
  SYSCALL(126, sched_get_priority_min) \
  SYSCALL(127, sched_rr_get_interval) \
  SYSCALL(128, unimplemented) \
  SYSCALL(129, kill) \
  SYSCALL(130, tkill) \
  SYSCALL(131, tgkill) \
  SYSCALL(132, sigaltstack) \
  SYSCALL(133, rt_sigsuspend) \
  SYSCALL(134, rt_sigaction) \
  SYSCALL(135, rt_sigprocmask) \
  SYSCALL(136, rt_sigpending) \
  SYSCALL(137, unimplemented) \
  SYSCALL(138, unimplemented) \
  SYSCALL(139, rt_sigreturn) \
  SYSCALL(140, setpriority) \
  SYSCALL(141, getpriority) \
  SYSCALL(142, unimplemented) \
  SYSCALL(143, unimplemented) \
  SYSCALL(144, setgid) \
  SYSCALL(145, unimplemented) \
  SYSCALL(146, setuid) \
  SYSCALL(147, setresuid) \
  SYSCALL(148, getresuid) \
  SYSCALL(149, setresgid) \
  SYSCALL(150, getresgid) \
  SYSCALL(151, unimplemented) \
  SYSCALL(152, unimplemented) \
  SYSCALL(153, unimplemented) \
  SYSCALL(154, setpgid) \
  SYSCALL(155, getpgid) \
  SYSCALL(156, getsid) \
  SYSCALL(157, setsid) \
  SYSCALL(158, getgroups) \
  SYSCALL(159, setgroups) \
  SYSCALL(160, uname) \
  SYSCALL(161, sethostname) \
  SYSCALL(162, setdomainname) \
  SYSCALL(163, getrlimit) \
  SYSCALL(164, setrlimit) \
  SYSCALL(165, getrusage) \
  SYSCALL(166, umask) \
  SYSCALL(167, prctl) \
  SYSCALL(168, unimplemented) \
  SYSCALL(169, gettimeofday) \
  SYSCALL(170, unimplemented) \
  SYSCALL(171, unimplemented) \
  SYSCALL(172, getpid) \
  SYSCALL(173, getppid) \
  SYSCALL(174, getuid) \
  SYSCALL(175, geteuid) \
  SYSCALL(176, getgid) \
  SYSCALL(177, getegid) \
  SYSCALL(178, gettid) \
  SYSCALL(179, sysinfo) \
  SYSCALL(180, unimplemented) \
  SYSCALL(181, unimplemented) \
  SYSCALL(182, unimplemented) \
  SYSCALL(183, unimplemented) \
  SYSCALL(184, unimplemented) \
  SYSCALL(185, unimplemented) \
  SYSCALL(186, msgget) \
  SYSCALL(187, msgctl) \
  SYSCALL(188, msgrcv) \
  SYSCALL(189, msgsnd) \
  SYSCALL(190, semget) \
  SYSCALL(191, semctl) \
  SYSCALL(192, semtimedop) \
  SYSCALL(193, semop) \
  SYSCALL(194, shmget) \
  SYSCALL(195, shmctl) \
  SYSCALL(196, shmat) \
  SYSCALL(197, shmdt) \
  SYSCALL(198, socket) \
  SYSCALL(199, socketpair) \
  SYSCALL(200, bind) \
  SYSCALL(201, listen) \
  SYSCALL(202, accept) \
  SYSCALL(203, connect) \
  SYSCALL(204, getsockname) \
  SYSCALL(205, getpeername) \
  SYSCALL(206, sendto) \
  SYSCALL(207, recvfrom) \
  SYSCALL(208, setsockopt) \
  SYSCALL(209, getsockopt) \
  SYSCALL(210, shutdown) \
  SYSCALL(211, sendmsg) \
  SYSCALL(212, recvmsg) \
  SYSCALL(213, unimplemented) \
  SYSCALL(214, brk) \
  SYSCALL(215, munmap) \
  SYSCALL(216, mremap) \
  SYSCALL(217, unimplemented) \
  SYSCALL(218, unimplemented) \
  SYSCALL(219, unimplemented) \
  SYSCALL(220, clone) \
  SYSCALL(221, execve) \
  SYSCALL(222, mmap) \
  SYSCALL(223, fadvise64) \
  SYSCALL(224, unimplemented) \
  SYSCALL(225, unimplemented) \
  SYSCALL(226, mprotect) \
  SYSCALL(227, msync) \
  SYSCALL(228, mlock) \
  SYSCALL(229, munlock) \
  SYSCALL(230, unimplemented) \
  SYSCALL(231, unimplemented) \
  SYSCALL(232, unimplemented) \
  SYSCALL(233, madvise) \
  SYSCALL(234, unimplemented) \
  SYSCALL(235, unimplemented) \
  SYSCALL(236, get_mempolicy) \
  SYSCALL(237, unimplemented) \
  SYSCALL(238, unimplemented) \
  SYSCALL(239, unimplemented) \
  SYSCALL(240, unimplemented) \
  SYSCALL(241, unimplemented) \
  SYSCALL(242, unimplemented) \
  SYSCALL(243, unimplemented) \
  SYSCALL(244, unimplemented) \
  SYSCALL(245, unimplemented) \
  SYSCALL(246, unimplemented) \
  SYSCALL(247, unimplemented) \
  SYSCALL(248, unimplemented) \
  SYSCALL(249, unimplemented) \
  SYSCALL(250, unimplemented) \
  SYSCALL(251, unimplemented) \
  SYSCALL(252, unimplemented) \
  SYSCALL(253, unimplemented) \
  SYSCALL(254, unimplemented) \
  SYSCALL(255, unimplemented) \
  SYSCALL(256, unimplemented) \
  SYSCALL(257, unimplemented) \
  SYSCALL(258, unimplemented) \
  SYSCALL(259, unimplemented) \
  SYSCALL(260, wait4) \
  SYSCALL(261, prlimit64) \
  SYSCALL(262, fanotify_init) \
  SYSCALL(263, fanotify_mark) \
  SYSCALL(264, name_to_handle_at) \
  SYSCALL(265, open_by_handle_at) \
  SYSCALL(266, unimplemented) \
  SYSCALL(267, syncfs) \
  SYSCALL(268, setns) \
  SYSCALL(269, sendmmsg) \
  SYSCALL(270, unimplemented) \
  SYSCALL(271, unimplemented) \
  SYSCALL(272, unimplemented) \
  SYSCALL(273, unimplemented) \
  SYSCALL(274, unimplemented) \
  SYSCALL(275, unimplemented) \
  SYSCALL(276, unimplemented) \
  SYSCALL(277, unimplemented) \
  SYSCALL(278, getrandom) \
  SYSCALL(279, unimplemented) \
  SYSCALL(280, unimplemented) \
  SYSCALL(281, unimplemented) \
  SYSCALL(282, unimplemented) \
  SYSCALL(283, unimplemented) \
  SYSCALL(284, unimplemented) \
  SYSCALL(285, copy_file_range) \
  SYSCALL(286, unimplemented) \
  SYSCALL(287, unimplemented) \
  SYSCALL(288, unimplemented) \
  SYSCALL(289, unimplemented) \
  SYSCALL(290, unimplemented) \
  SYSCALL(291, statx) \
  SYSCALL(292, io_pgetevents) \
  SYSCALL(293, rseq) \
  SYSCALL(294, unimplemented) \
  SYSCALL(295, unimplemented) \
  SYSCALL(296, unimplemented) \
  SYSCALL(297, unimplemented) \
  SYSCALL(298, unimplemented) \
  SYSCALL(299, unimplemented) \
  SYSCALL(300, unimplemented) \
  SYSCALL(301, unimplemented) \
  SYSCALL(302, unimplemented) \
  SYSCALL(303, unimplemented) \
  SYSCALL(304, unimplemented) \
  SYSCALL(305, unimplemented) \
  SYSCALL(306, unimplemented) \
  SYSCALL(307, unimplemented) \
  SYSCALL(308, unimplemented) \
  SYSCALL(309, unimplemented) \
  SYSCALL(310, unimplemented) \
  SYSCALL(311, unimplemented) \
  SYSCALL(312, unimplemented) \
  SYSCALL(313, unimplemented) \
  SYSCALL(314, unimplemented) \
  SYSCALL(315, unimplemented) \
  SYSCALL(316, unimplemented) \
  SYSCALL(317, unimplemented) \
  SYSCALL(318, unimplemented) \
  SYSCALL(319, unimplemented) \
  SYSCALL(320, unimplemented) \
  SYSCALL(321, unimplemented) \
  SYSCALL(322, unimplemented) \
  SYSCALL(323, unimplemented) \
  SYSCALL(324, unimplemented) \
  SYSCALL(325, unimplemented) \
  SYSCALL(326, unimplemented) \
  SYSCALL(327, unimplemented) \
  SYSCALL(328, unimplemented) \
  SYSCALL(329, unimplemented) \
  SYSCALL(330, unimplemented) \
  SYSCALL(331, unimplemented) \
  SYSCALL(332, unimplemented) \
  SYSCALL(333, unimplemented) \
  SYSCALL(334, unimplemented) \
  SYSCALL(335, unimplemented) \
  SYSCALL(336, unimplemented) \
  SYSCALL(337, unimplemented) \
  SYSCALL(338, unimplemented) \
  SYSCALL(339, unimplemented) \
  SYSCALL(340, unimplemented) \
  SYSCALL(341, unimplemented) \
  SYSCALL(342, unimplemented) \
  SYSCALL(343, unimplemented) \
  SYSCALL(344, unimplemented) \
  SYSCALL(345, unimplemented) \
  SYSCALL(346, unimplemented) \
  SYSCALL(347, unimplemented) \
  SYSCALL(348, unimplemented) \
  SYSCALL(349, unimplemented) \
  SYSCALL(350, unimplemented) \
  SYSCALL(351, unimplemented) \
  SYSCALL(352, unimplemented) \
  SYSCALL(353, unimplemented) \
  SYSCALL(354, unimplemented) \
  SYSCALL(355, unimplemented) \
  SYSCALL(356, unimplemented) \
  SYSCALL(357, unimplemented) \
  SYSCALL(358, unimplemented) \
  SYSCALL(359, unimplemented) \
  SYSCALL(360, unimplemented) \
  SYSCALL(361, unimplemented) \
  SYSCALL(362, unimplemented) \
  SYSCALL(363, unimplemented) \
  SYSCALL(364, unimplemented) \
  SYSCALL(365, unimplemented) \
  SYSCALL(366, unimplemented) \
  SYSCALL(367, unimplemented) \
  SYSCALL(368, unimplemented) \
  SYSCALL(369, unimplemented) \
  SYSCALL(370, unimplemented) \
  SYSCALL(371, unimplemented) \
  SYSCALL(372, unimplemented) \
  SYSCALL(373, unimplemented) \
  SYSCALL(374, unimplemented) \
  SYSCALL(375, unimplemented) \
  SYSCALL(376, unimplemented) \
  SYSCALL(377, unimplemented) \
  SYSCALL(378, unimplemented) \
  SYSCALL(379, unimplemented) \
  SYSCALL(380, unimplemented) \
  SYSCALL(381, unimplemented) \
  SYSCALL(382, unimplemented) \
  SYSCALL(383, unimplemented) \
  SYSCALL(384, unimplemented) \
  SYSCALL(385, unimplemented) \
  SYSCALL(386, unimplemented) \
  SYSCALL(387, unimplemented) \
  SYSCALL(388, unimplemented) \
  SYSCALL(389, unimplemented) \
  SYSCALL(390, unimplemented) \
  SYSCALL(391, unimplemented) \
  SYSCALL(392, unimplemented) \
  SYSCALL(393, unimplemented) \
  SYSCALL(394, unimplemented) \
  SYSCALL(395, unimplemented) \
  SYSCALL(396, unimplemented) \
  SYSCALL(397, unimplemented) \
  SYSCALL(398, unimplemented) \
  SYSCALL(399, unimplemented) \
  SYSCALL(400, unimplemented) \
  SYSCALL(401, unimplemented) \
  SYSCALL(402, unimplemented) \
  SYSCALL(403, unimplemented) \
  SYSCALL(404, unimplemented) \
  SYSCALL(405, unimplemented) \
  SYSCALL(406, unimplemented) \
  SYSCALL(407, unimplemented) \
  SYSCALL(408, unimplemented) \
  SYSCALL(409, unimplemented) \
  SYSCALL(410, unimplemented) \
  SYSCALL(411, unimplemented) \
  SYSCALL(412, unimplemented) \
  SYSCALL(413, unimplemented) \
  SYSCALL(414, unimplemented) \
  SYSCALL(415, unimplemented) \
  SYSCALL(416, unimplemented) \
  SYSCALL(417, unimplemented) \
  SYSCALL(418, unimplemented) \
  SYSCALL(419, unimplemented) \
  SYSCALL(420, unimplemented) \
  SYSCALL(421, unimplemented) \
  SYSCALL(422, unimplemented) \
  SYSCALL(423, unimplemented) \
  SYSCALL(424, unimplemented) \
  SYSCALL(425, io_uring_setup) \
  SYSCALL(426, io_uring_enter) \
  SYSCALL(427, io_uring_register) \
  SYSCALL(428, unimplemented) \
  SYSCALL(429, unimplemented) \
  SYSCALL(430, unimplemented) \
  SYSCALL(431, unimplemented) \
  SYSCALL(432, unimplemented) \
  SYSCALL(433, unimplemented) \
  SYSCALL(434, unimplemented) \
  SYSCALL(435, clone3) \
  SYSCALL(436, unimplemented) \
  SYSCALL(437, unimplemented) \
  SYSCALL(438, unimplemented) \
  SYSCALL(439, faccessat2) \
  SYSCALL(440, unimplemented) \
  SYSCALL(441, unimplemented) \
  SYSCALL(442, unimplemented) \
  SYSCALL(443, unimplemented) \
  SYSCALL(444, unimplemented) \
  SYSCALL(445, unimplemented) \
  SYSCALL(446, unimplemented) \
  SYSCALL(447, unimplemented) \
  SYSCALL(448, unimplemented) \
  SYSCALL(449, futex_waitv) \
  SYSCALL(450, unimplemented) \
  SYSCALL(451, unimplemented) \
  SYSCALL(452, unimplemented) \
  SYSCALL(453, unimplemented) \
  SYSCALL(454, futex_wake) \
  SYSCALL(455, futex_wait) \
  SYSCALL(456, futex_requeue) \
  SYSCALL(457, unimplemented) \
  SYSCALL(458, unimplemented) \
  SYSCALL(459, unimplemented) \
  SYSCALL(460, unimplemented) \
  SYSCALL(461, unimplemented) \
  SYSCALL(462, unimplemented) \
  /* Numbers Linux has not allocated. Left explicitly empty so that the \
   * compat tail below cannot be mistaken for them. */ \
  SYSCALL(463, unimplemented) \
  SYSCALL(464, unimplemented) \
  SYSCALL(465, unimplemented) \
  SYSCALL(466, unimplemented) \
  SYSCALL(467, unimplemented) \
  SYSCALL(468, unimplemented) \
  SYSCALL(469, unimplemented) \
  SYSCALL(470, unimplemented) \
  SYSCALL(471, unimplemented) \
  SYSCALL(472, unimplemented) \
  SYSCALL(473, unimplemented) \
  SYSCALL(474, unimplemented) \
  SYSCALL(475, unimplemented) \
  SYSCALL(476, unimplemented) \
  SYSCALL(477, unimplemented) \
  SYSCALL(478, unimplemented) \
  SYSCALL(479, unimplemented) \
  SYSCALL(480, unimplemented) \
  SYSCALL(481, unimplemented) \
  SYSCALL(482, unimplemented) \
  SYSCALL(483, unimplemented) \
  SYSCALL(484, unimplemented) \
  SYSCALL(485, unimplemented) \
  SYSCALL(486, unimplemented) \
  SYSCALL(487, unimplemented) \
  SYSCALL(488, unimplemented) \
  SYSCALL(489, unimplemented) \
  SYSCALL(490, unimplemented) \
  SYSCALL(491, unimplemented) \
  SYSCALL(492, unimplemented) \
  SYSCALL(493, unimplemented) \
  SYSCALL(494, unimplemented) \
  SYSCALL(495, unimplemented) \
  SYSCALL(496, unimplemented) \
  SYSCALL(497, unimplemented) \
  SYSCALL(498, unimplemented) \
  SYSCALL(499, unimplemented) \
  SYSCALL(500, unimplemented) \
  SYSCALL(501, unimplemented) \
  SYSCALL(502, unimplemented) \
  SYSCALL(503, unimplemented) \
  SYSCALL(504, unimplemented) \
  SYSCALL(505, unimplemented) \
  SYSCALL(506, unimplemented) \
  SYSCALL(507, unimplemented) \
  SYSCALL(508, unimplemented) \
  SYSCALL(509, unimplemented) \
  SYSCALL(510, unimplemented) \
  SYSCALL(511, unimplemented) \
  SYSCALL(512, unimplemented) \
  SYSCALL(513, unimplemented) \
  SYSCALL(514, unimplemented) \
  SYSCALL(515, unimplemented) \
  SYSCALL(516, unimplemented) \
  SYSCALL(517, unimplemented) \
  SYSCALL(518, unimplemented) \
  SYSCALL(519, unimplemented) \
  SYSCALL(520, unimplemented) \
  SYSCALL(521, unimplemented) \
  SYSCALL(522, unimplemented) \
  SYSCALL(523, unimplemented) \
  SYSCALL(524, unimplemented) \
  SYSCALL(525, unimplemented) \
  SYSCALL(526, unimplemented) \
  SYSCALL(527, unimplemented) \
  SYSCALL(528, unimplemented) \
  SYSCALL(529, unimplemented) \
  SYSCALL(530, unimplemented) \
  SYSCALL(531, unimplemented) \
  SYSCALL(532, unimplemented) \
  SYSCALL(533, unimplemented) \
  SYSCALL(534, unimplemented) \
  SYSCALL(535, unimplemented) \
  SYSCALL(536, unimplemented) \
  SYSCALL(537, unimplemented) \
  SYSCALL(538, unimplemented) \
  SYSCALL(539, unimplemented) \
  SYSCALL(540, unimplemented) \
  SYSCALL(541, unimplemented) \
  SYSCALL(542, unimplemented) \
  SYSCALL(543, unimplemented) \
  SYSCALL(544, unimplemented) \
  SYSCALL(545, unimplemented) \
  SYSCALL(546, unimplemented) \
  SYSCALL(547, unimplemented) \
  SYSCALL(548, unimplemented) \
  SYSCALL(549, unimplemented) \
  SYSCALL(550, unimplemented) \
  SYSCALL(551, unimplemented) \
  SYSCALL(552, unimplemented) \
  SYSCALL(553, unimplemented) \
  SYSCALL(554, unimplemented) \
  SYSCALL(555, unimplemented) \
  SYSCALL(556, unimplemented) \
  SYSCALL(557, unimplemented) \
  SYSCALL(558, unimplemented) \
  SYSCALL(559, unimplemented) \
  SYSCALL(560, unimplemented) \
  SYSCALL(561, unimplemented) \
  SYSCALL(562, unimplemented) \
  SYSCALL(563, unimplemented) \
  SYSCALL(564, unimplemented) \
  SYSCALL(565, unimplemented) \
  SYSCALL(566, unimplemented) \
  SYSCALL(567, unimplemented) \
  SYSCALL(568, unimplemented) \
  SYSCALL(569, unimplemented) \
  SYSCALL(570, unimplemented) \
  SYSCALL(571, unimplemented) \
  SYSCALL(572, unimplemented) \
  SYSCALL(573, unimplemented) \
  SYSCALL(574, unimplemented) \
  SYSCALL(575, unimplemented) \
  SYSCALL(576, unimplemented) \
  SYSCALL(577, unimplemented) \
  SYSCALL(578, unimplemented) \
  SYSCALL(579, unimplemented) \
  SYSCALL(580, unimplemented) \
  SYSCALL(581, unimplemented) \
  SYSCALL(582, unimplemented) \
  SYSCALL(583, unimplemented) \
  SYSCALL(584, unimplemented) \
  SYSCALL(585, unimplemented) \
  SYSCALL(586, unimplemented) \
  SYSCALL(587, unimplemented) \
  SYSCALL(588, unimplemented) \
  SYSCALL(589, unimplemented) \
  SYSCALL(590, unimplemented) \
  SYSCALL(591, unimplemented) \
  SYSCALL(592, unimplemented) \
  SYSCALL(593, unimplemented) \
  SYSCALL(594, unimplemented) \
  SYSCALL(595, unimplemented) \
  SYSCALL(596, unimplemented) \
  SYSCALL(597, unimplemented) \
  SYSCALL(598, unimplemented) \
  SYSCALL(599, unimplemented) \
  SYSCALL(600, unimplemented) \
  SYSCALL(601, unimplemented) \
  SYSCALL(602, unimplemented) \
  SYSCALL(603, unimplemented) \
  SYSCALL(604, unimplemented) \
  SYSCALL(605, unimplemented) \
  SYSCALL(606, unimplemented) \
  SYSCALL(607, unimplemented) \
  SYSCALL(608, unimplemented) \
  SYSCALL(609, unimplemented) \
  SYSCALL(610, unimplemented) \
  SYSCALL(611, unimplemented) \
  SYSCALL(612, unimplemented) \
  SYSCALL(613, unimplemented) \
  SYSCALL(614, unimplemented) \
  SYSCALL(615, unimplemented) \
  SYSCALL(616, unimplemented) \
  SYSCALL(617, unimplemented) \
  SYSCALL(618, unimplemented) \
  SYSCALL(619, unimplemented) \
  SYSCALL(620, unimplemented) \
  SYSCALL(621, unimplemented) \
  SYSCALL(622, unimplemented) \
  SYSCALL(623, unimplemented) \
  SYSCALL(624, unimplemented) \
  SYSCALL(625, unimplemented) \
  SYSCALL(626, unimplemented) \
  SYSCALL(627, unimplemented) \
  SYSCALL(628, unimplemented) \
  SYSCALL(629, unimplemented) \
  SYSCALL(630, unimplemented) \
  SYSCALL(631, unimplemented) \
  SYSCALL(632, unimplemented) \
  SYSCALL(633, unimplemented) \
  SYSCALL(634, unimplemented) \
  SYSCALL(635, unimplemented) \
  SYSCALL(636, unimplemented) \
  SYSCALL(637, unimplemented) \
  SYSCALL(638, unimplemented) \
  SYSCALL(639, unimplemented) \
  SYSCALL(640, unimplemented) \
  SYSCALL(641, unimplemented) \
  SYSCALL(642, unimplemented) \
  SYSCALL(643, unimplemented) \
  SYSCALL(644, unimplemented) \
  SYSCALL(645, unimplemented) \
  SYSCALL(646, unimplemented) \
  SYSCALL(647, unimplemented) \
  SYSCALL(648, unimplemented) \
  SYSCALL(649, unimplemented) \
  SYSCALL(650, unimplemented) \
  SYSCALL(651, unimplemented) \
  SYSCALL(652, unimplemented) \
  SYSCALL(653, unimplemented) \
  SYSCALL(654, unimplemented) \
  SYSCALL(655, unimplemented) \
  SYSCALL(656, unimplemented) \
  SYSCALL(657, unimplemented) \
  SYSCALL(658, unimplemented) \
  SYSCALL(659, unimplemented) \
  SYSCALL(660, unimplemented) \
  SYSCALL(661, unimplemented) \
  SYSCALL(662, unimplemented) \
  SYSCALL(663, unimplemented) \
  SYSCALL(664, unimplemented) \
  SYSCALL(665, unimplemented) \
  SYSCALL(666, unimplemented) \
  SYSCALL(667, unimplemented) \
  SYSCALL(668, unimplemented) \
  SYSCALL(669, unimplemented) \
  SYSCALL(670, unimplemented) \
  SYSCALL(671, unimplemented) \
  SYSCALL(672, unimplemented) \
  SYSCALL(673, unimplemented) \
  SYSCALL(674, unimplemented) \
  SYSCALL(675, unimplemented) \
  SYSCALL(676, unimplemented) \
  SYSCALL(677, unimplemented) \
  SYSCALL(678, unimplemented) \
  SYSCALL(679, unimplemented) \
  SYSCALL(680, unimplemented) \
  SYSCALL(681, unimplemented) \
  SYSCALL(682, unimplemented) \
  SYSCALL(683, unimplemented) \
  SYSCALL(684, unimplemented) \
  SYSCALL(685, unimplemented) \
  SYSCALL(686, unimplemented) \
  SYSCALL(687, unimplemented) \
  SYSCALL(688, unimplemented) \
  SYSCALL(689, unimplemented) \
  SYSCALL(690, unimplemented) \
  SYSCALL(691, unimplemented) \
  SYSCALL(692, unimplemented) \
  SYSCALL(693, unimplemented) \
  SYSCALL(694, unimplemented) \
  SYSCALL(695, unimplemented) \
  SYSCALL(696, unimplemented) \
  SYSCALL(697, unimplemented) \
  SYSCALL(698, unimplemented) \
  SYSCALL(699, unimplemented) \
  SYSCALL(700, unimplemented) \
  SYSCALL(701, unimplemented) \
  SYSCALL(702, unimplemented) \
  SYSCALL(703, unimplemented) \
  SYSCALL(704, unimplemented) \
  SYSCALL(705, unimplemented) \
  SYSCALL(706, unimplemented) \
  SYSCALL(707, unimplemented) \
  SYSCALL(708, unimplemented) \
  SYSCALL(709, unimplemented) \
  SYSCALL(710, unimplemented) \
  SYSCALL(711, unimplemented) \
  SYSCALL(712, unimplemented) \
  SYSCALL(713, unimplemented) \
  SYSCALL(714, unimplemented) \
  SYSCALL(715, unimplemented) \
  SYSCALL(716, unimplemented) \
  SYSCALL(717, unimplemented) \
  SYSCALL(718, unimplemented) \
  SYSCALL(719, unimplemented) \
  SYSCALL(720, unimplemented) \
  SYSCALL(721, unimplemented) \
  SYSCALL(722, unimplemented) \
  SYSCALL(723, unimplemented) \
  SYSCALL(724, unimplemented) \
  SYSCALL(725, unimplemented) \
  SYSCALL(726, unimplemented) \
  SYSCALL(727, unimplemented) \
  SYSCALL(728, unimplemented) \
  SYSCALL(729, unimplemented) \
  SYSCALL(730, unimplemented) \
  SYSCALL(731, unimplemented) \
  SYSCALL(732, unimplemented) \
  SYSCALL(733, unimplemented) \
  SYSCALL(734, unimplemented) \
  SYSCALL(735, unimplemented) \
  SYSCALL(736, unimplemented) \
  SYSCALL(737, unimplemented) \
  SYSCALL(738, unimplemented) \
  SYSCALL(739, unimplemented) \
  SYSCALL(740, unimplemented) \
  SYSCALL(741, unimplemented) \
  SYSCALL(742, unimplemented) \
  SYSCALL(743, unimplemented) \
  SYSCALL(744, unimplemented) \
  SYSCALL(745, unimplemented) \
  SYSCALL(746, unimplemented) \
  SYSCALL(747, unimplemented) \
  SYSCALL(748, unimplemented) \
  SYSCALL(749, unimplemented) \
  SYSCALL(750, unimplemented) \
  SYSCALL(751, unimplemented) \
  SYSCALL(752, unimplemented) \
  SYSCALL(753, unimplemented) \
  SYSCALL(754, unimplemented) \
  SYSCALL(755, unimplemented) \
  SYSCALL(756, unimplemented) \
  SYSCALL(757, unimplemented) \
  SYSCALL(758, unimplemented) \
  SYSCALL(759, unimplemented) \
  SYSCALL(760, unimplemented) \
  SYSCALL(761, unimplemented) \
  SYSCALL(762, unimplemented) \
  SYSCALL(763, unimplemented) \
  SYSCALL(764, unimplemented) \
  SYSCALL(765, unimplemented) \
  SYSCALL(766, unimplemented) \
  SYSCALL(767, unimplemented) \
  SYSCALL(768, unimplemented) \
  SYSCALL(769, unimplemented) \
  SYSCALL(770, unimplemented) \
  SYSCALL(771, unimplemented) \
  SYSCALL(772, unimplemented) \
  SYSCALL(773, unimplemented) \
  SYSCALL(774, unimplemented) \
  SYSCALL(775, unimplemented) \
  SYSCALL(776, unimplemented) \
  SYSCALL(777, unimplemented) \
  SYSCALL(778, unimplemented) \
  SYSCALL(779, unimplemented) \
  SYSCALL(780, unimplemented) \
  SYSCALL(781, unimplemented) \
  SYSCALL(782, unimplemented) \
  SYSCALL(783, unimplemented) \
  SYSCALL(784, unimplemented) \
  SYSCALL(785, unimplemented) \
  SYSCALL(786, unimplemented) \
  SYSCALL(787, unimplemented) \
  SYSCALL(788, unimplemented) \
  SYSCALL(789, unimplemented) \
  SYSCALL(790, unimplemented) \
  SYSCALL(791, unimplemented) \
  SYSCALL(792, unimplemented) \
  SYSCALL(793, unimplemented) \
  SYSCALL(794, unimplemented) \
  SYSCALL(795, unimplemented) \
  SYSCALL(796, unimplemented) \
  SYSCALL(797, unimplemented) \
  SYSCALL(798, unimplemented) \
  SYSCALL(799, unimplemented) \
  SYSCALL(800, unimplemented) \
  SYSCALL(801, unimplemented) \
  SYSCALL(802, unimplemented) \
  SYSCALL(803, unimplemented) \
  SYSCALL(804, unimplemented) \
  SYSCALL(805, unimplemented) \
  SYSCALL(806, unimplemented) \
  SYSCALL(807, unimplemented) \
  SYSCALL(808, unimplemented) \
  SYSCALL(809, unimplemented) \
  SYSCALL(810, unimplemented) \
  SYSCALL(811, unimplemented) \
  SYSCALL(812, unimplemented) \
  SYSCALL(813, unimplemented) \
  SYSCALL(814, unimplemented) \
  SYSCALL(815, unimplemented) \
  SYSCALL(816, unimplemented) \
  SYSCALL(817, unimplemented) \
  SYSCALL(818, unimplemented) \
  SYSCALL(819, unimplemented) \
  SYSCALL(820, unimplemented) \
  SYSCALL(821, unimplemented) \
  SYSCALL(822, unimplemented) \
  SYSCALL(823, unimplemented) \
  SYSCALL(824, unimplemented) \
  SYSCALL(825, unimplemented) \
  SYSCALL(826, unimplemented) \
  SYSCALL(827, unimplemented) \
  SYSCALL(828, unimplemented) \
  SYSCALL(829, unimplemented) \
  SYSCALL(830, unimplemented) \
  SYSCALL(831, unimplemented) \
  SYSCALL(832, unimplemented) \
  SYSCALL(833, unimplemented) \
  SYSCALL(834, unimplemented) \
  SYSCALL(835, unimplemented) \
  SYSCALL(836, unimplemented) \
  SYSCALL(837, unimplemented) \
  SYSCALL(838, unimplemented) \
  SYSCALL(839, unimplemented) \
  SYSCALL(840, unimplemented) \
  SYSCALL(841, unimplemented) \
  SYSCALL(842, unimplemented) \
  SYSCALL(843, unimplemented) \
  SYSCALL(844, unimplemented) \
  SYSCALL(845, unimplemented) \
  SYSCALL(846, unimplemented) \
  SYSCALL(847, unimplemented) \
  SYSCALL(848, unimplemented) \
  SYSCALL(849, unimplemented) \
  SYSCALL(850, unimplemented) \
  SYSCALL(851, unimplemented) \
  SYSCALL(852, unimplemented) \
  SYSCALL(853, unimplemented) \
  SYSCALL(854, unimplemented) \
  SYSCALL(855, unimplemented) \
  SYSCALL(856, unimplemented) \
  SYSCALL(857, unimplemented) \
  SYSCALL(858, unimplemented) \
  SYSCALL(859, unimplemented) \
  SYSCALL(860, unimplemented) \
  SYSCALL(861, unimplemented) \
  SYSCALL(862, unimplemented) \
  SYSCALL(863, unimplemented) \
  SYSCALL(864, unimplemented) \
  SYSCALL(865, unimplemented) \
  SYSCALL(866, unimplemented) \
  SYSCALL(867, unimplemented) \
  SYSCALL(868, unimplemented) \
  SYSCALL(869, unimplemented) \
  SYSCALL(870, unimplemented) \
  SYSCALL(871, unimplemented) \
  SYSCALL(872, unimplemented) \
  SYSCALL(873, unimplemented) \
  SYSCALL(874, unimplemented) \
  SYSCALL(875, unimplemented) \
  SYSCALL(876, unimplemented) \
  SYSCALL(877, unimplemented) \
  SYSCALL(878, unimplemented) \
  SYSCALL(879, unimplemented) \
  SYSCALL(880, unimplemented) \
  SYSCALL(881, unimplemented) \
  SYSCALL(882, unimplemented) \
  SYSCALL(883, unimplemented) \
  SYSCALL(884, unimplemented) \
  SYSCALL(885, unimplemented) \
  SYSCALL(886, unimplemented) \
  SYSCALL(887, unimplemented) \
  SYSCALL(888, unimplemented) \
  SYSCALL(889, unimplemented) \
  SYSCALL(890, unimplemented) \
  SYSCALL(891, unimplemented) \
  SYSCALL(892, unimplemented) \
  SYSCALL(893, unimplemented) \
  SYSCALL(894, unimplemented) \
  SYSCALL(895, unimplemented) \
  SYSCALL(896, unimplemented) \
  SYSCALL(897, unimplemented) \
  SYSCALL(898, unimplemented) \
  SYSCALL(899, unimplemented) \
  SYSCALL(900, unimplemented) \
  SYSCALL(901, unimplemented) \
  SYSCALL(902, unimplemented) \
  SYSCALL(903, unimplemented) \
  SYSCALL(904, unimplemented) \
  SYSCALL(905, unimplemented) \
  SYSCALL(906, unimplemented) \
  SYSCALL(907, unimplemented) \
  SYSCALL(908, unimplemented) \
  SYSCALL(909, unimplemented) \
  SYSCALL(910, unimplemented) \
  SYSCALL(911, unimplemented) \
  SYSCALL(912, unimplemented) \
  SYSCALL(913, unimplemented) \
  SYSCALL(914, unimplemented) \
  SYSCALL(915, unimplemented) \
  SYSCALL(916, unimplemented) \
  SYSCALL(917, unimplemented) \
  SYSCALL(918, unimplemented) \
  SYSCALL(919, unimplemented) \
  SYSCALL(920, unimplemented) \
  SYSCALL(921, unimplemented) \
  SYSCALL(922, unimplemented) \
  SYSCALL(923, unimplemented) \
  SYSCALL(924, unimplemented) \
  SYSCALL(925, unimplemented) \
  SYSCALL(926, unimplemented) \
  SYSCALL(927, unimplemented) \
  SYSCALL(928, unimplemented) \
  SYSCALL(929, unimplemented) \
  SYSCALL(930, unimplemented) \
  SYSCALL(931, unimplemented) \
  SYSCALL(932, unimplemented) \
  SYSCALL(933, unimplemented) \
  SYSCALL(934, unimplemented) \
  SYSCALL(935, unimplemented) \
  SYSCALL(936, unimplemented) \
  SYSCALL(937, unimplemented) \
  SYSCALL(938, unimplemented) \
  SYSCALL(939, unimplemented) \
  SYSCALL(940, unimplemented) \
  SYSCALL(941, unimplemented) \
  SYSCALL(942, unimplemented) \
  SYSCALL(943, unimplemented) \
  SYSCALL(944, unimplemented) \
  SYSCALL(945, unimplemented) \
  SYSCALL(946, unimplemented) \
  SYSCALL(947, unimplemented) \
  SYSCALL(948, unimplemented) \
  SYSCALL(949, unimplemented) \
  SYSCALL(950, unimplemented) \
  SYSCALL(951, unimplemented) \
  SYSCALL(952, unimplemented) \
  SYSCALL(953, unimplemented) \
  SYSCALL(954, unimplemented) \
  SYSCALL(955, unimplemented) \
  SYSCALL(956, unimplemented) \
  SYSCALL(957, unimplemented) \
  SYSCALL(958, unimplemented) \
  SYSCALL(959, unimplemented) \
  SYSCALL(960, unimplemented) \
  SYSCALL(961, unimplemented) \
  SYSCALL(962, unimplemented) \
  SYSCALL(963, unimplemented) \
  SYSCALL(964, unimplemented) \
  SYSCALL(965, unimplemented) \
  SYSCALL(966, unimplemented) \
  SYSCALL(967, unimplemented) \
  SYSCALL(968, unimplemented) \
  SYSCALL(969, unimplemented) \
  SYSCALL(970, unimplemented) \
  SYSCALL(971, unimplemented) \
  SYSCALL(972, unimplemented) \
  SYSCALL(973, unimplemented) \
  SYSCALL(974, unimplemented) \
  SYSCALL(975, unimplemented) \
  SYSCALL(976, unimplemented) \
  SYSCALL(977, unimplemented) \
  SYSCALL(978, unimplemented) \
  SYSCALL(979, unimplemented) \
  SYSCALL(980, unimplemented) \
  SYSCALL(981, unimplemented) \
  SYSCALL(982, unimplemented) \
  SYSCALL(983, unimplemented) \
  SYSCALL(984, unimplemented) \
  SYSCALL(985, unimplemented) \
  SYSCALL(986, unimplemented) \
  SYSCALL(987, unimplemented) \
  SYSCALL(988, unimplemented) \
  SYSCALL(989, unimplemented) \
  SYSCALL(990, unimplemented) \
  SYSCALL(991, unimplemented) \
  SYSCALL(992, unimplemented) \
  SYSCALL(993, unimplemented) \
  SYSCALL(994, unimplemented) \
  SYSCALL(995, unimplemented) \
  SYSCALL(996, unimplemented) \
  SYSCALL(997, unimplemented) \
  SYSCALL(998, unimplemented) \
  SYSCALL(999, unimplemented) \
  SYSCALL(1000, unimplemented) \
  SYSCALL(1001, unimplemented) \
  SYSCALL(1002, unimplemented) \
  SYSCALL(1003, unimplemented) \
  SYSCALL(1004, unimplemented) \
  SYSCALL(1005, unimplemented) \
  SYSCALL(1006, unimplemented) \
  SYSCALL(1007, unimplemented) \
  SYSCALL(1008, unimplemented) \
  SYSCALL(1009, unimplemented) \
  SYSCALL(1010, unimplemented) \
  SYSCALL(1011, unimplemented) \
  SYSCALL(1012, unimplemented) \
  SYSCALL(1013, unimplemented) \
  SYSCALL(1014, unimplemented) \
  SYSCALL(1015, unimplemented) \
  SYSCALL(1016, unimplemented) \
  SYSCALL(1017, unimplemented) \
  SYSCALL(1018, unimplemented) \
  SYSCALL(1019, unimplemented) \
  SYSCALL(1020, unimplemented) \
  SYSCALL(1021, unimplemented) \
  SYSCALL(1022, unimplemented) \
  SYSCALL(1023, unimplemented) \
  /* x86-legacy handlers with no aarch64 number - see the generator. */ \
  SYSCALL(1024, access) \
  SYSCALL(1025, afs_syscall) \
  SYSCALL(1026, alarm) \
  SYSCALL(1027, arch_prctl) \
  SYSCALL(1028, chmod) \
  SYSCALL(1029, chown) \
  SYSCALL(1030, creat) \
  SYSCALL(1031, dup2) \
  SYSCALL(1032, epoll_ctl_old) \
  SYSCALL(1033, epoll_wait_old) \
  SYSCALL(1034, fork) \
  SYSCALL(1035, get_thread_area) \
  SYSCALL(1036, getdents) \
  SYSCALL(1037, getpgrp) \
  SYSCALL(1038, getpmsg) \
  SYSCALL(1039, inotify_init) \
  SYSCALL(1040, lchown) \
  SYSCALL(1041, link) \
  SYSCALL(1042, lstat) \
  SYSCALL(1043, mkdir) \
  SYSCALL(1044, mknod) \
  SYSCALL(1045, open) \
  SYSCALL(1046, pipe) \
  SYSCALL(1047, poll) \
  SYSCALL(1048, putpmsg) \
  SYSCALL(1049, readlink) \
  SYSCALL(1050, rename) \
  SYSCALL(1051, rmdir) \
  SYSCALL(1052, security) \
  SYSCALL(1053, select) \
  SYSCALL(1054, set_thread_area) \
  SYSCALL(1055, stat) \
  SYSCALL(1056, symlink) \
  SYSCALL(1057, sysfs) \
  SYSCALL(1058, time) \
  SYSCALL(1059, tuxcall) \
  SYSCALL(1060, unimplemented) \
  SYSCALL(1061, unlink) \
  SYSCALL(1062, uselib) \
  SYSCALL(1063, utime) \
  SYSCALL(1064, utimes) \
  SYSCALL(1065, vfork) \
  SYSCALL(1066, vserver) \

#define NR_SYSCALLS 1067
